/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interfaz;

import SCORE.SCORE_PRINT;
import javax.swing.ImageIcon;


/**
 *
 * @author Portatil
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("War Table Hana");
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExit = new javax.swing.JButton();
        jDosJugadores = new javax.swing.JButton();
        jUnJugador = new javax.swing.JButton();
        jScore = new javax.swing.JButton();
        jSeparatorHorizontal = new javax.swing.JSeparator();
        jSeparatorVertical = new javax.swing.JSeparator();
        jLabelMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jExit.setForeground(new java.awt.Color(255, 255, 255));
        jExit.setText("EXIT");
        jExit.setBorderPainted(false);
        jExit.setContentAreaFilled(false);
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 400, 210));

        jDosJugadores.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jDosJugadores.setForeground(new java.awt.Color(255, 255, 255));
        jDosJugadores.setText("2 PLAYER");
        jDosJugadores.setBorderPainted(false);
        jDosJugadores.setContentAreaFilled(false);
        jDosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDosJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(jDosJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 190));

        jUnJugador.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jUnJugador.setForeground(new java.awt.Color(255, 255, 255));
        jUnJugador.setText("1 PLAYER");
        jUnJugador.setBorderPainted(false);
        jUnJugador.setContentAreaFilled(false);
        getContentPane().add(jUnJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jScore.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jScore.setForeground(new java.awt.Color(255, 255, 255));
        jScore.setText("BEST SCORE");
        jScore.setBorderPainted(false);
        jScore.setContentAreaFilled(false);
        jScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScoreActionPerformed(evt);
            }
        });
        getContentPane().add(jScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, 210));

        jSeparatorHorizontal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparatorHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 800, 40));

        jSeparatorVertical.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparatorVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 30, 400));

        jLabelMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cielo estrellado.png"))); // NOI18N
        getContentPane().add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void jDosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDosJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDosJugadoresActionPerformed

    private void jScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScoreActionPerformed
        // TODO add your handling code here:
        SCORE_PRINT obj=new SCORE_PRINT();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDosJugadores;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JButton jScore;
    private javax.swing.JSeparator jSeparatorHorizontal;
    private javax.swing.JSeparator jSeparatorVertical;
    private javax.swing.JButton jUnJugador;
    // End of variables declaration//GEN-END:variables
}
